### ISSUE TITLE
[question] Gitlab wants username even though api-token is provided

### ISSUE THREAD

**Issue by svdo** [chaoss/grimoirelab-sirmordred#338]
I'm experimenting with GrimoireLab, specifically attaching our enterprise gitlab. It looks awesome, I'm very enthusiastic about it!

I succeeded in getting `gitlab:issue` and `gitlab:merge_request` information. I'm not yet able to load the git information from gitlab from non-public projects though: I see in the output of the docker container a prompt for the "Username for '<our enterprise url>':", which should not be needed because of the API token.

So my question is: how do I configure things so that git data is pulled from gitlab using the API token: what do I need to put in the config file and what in the `projects.json`?

**Comment by valeriocos** [comment]
> I'm experimenting with GrimoireLab, specifically attaching our enterprise gitlab. It looks awesome, I'm very enthusiastic about it!

Hi @svdo , great, thanks for the feeback!

> ...how do I configure things so that git data is pulled from gitlab using the API token: what do I need to put in the config file and what in the projects.json?

A similar problem was reported for GitHub projects, so probably the solution is similar (https://github.com/chaoss/grimoirelab/issues/209, https://github.com/chaoss/grimoirelab/issues/205). In a nutshell, the git urls should include the gitlab username and token, like this: 
```
"...": {
    "git": [
        "https://<gitlab-user>:<token>@gitlab.com/..."
    ],
    ...
}
```
The token won't appear in the dashboard thanks to a recent fix: https://github.com/chaoss/grimoirelab-elk/pull/682

Let us know if this solves your problem, thanks

**Comment by svdo** [comment]
Thanks so much for your super fast response @valeriocos!!

I just tried your suggestion. It never occurred to me that I might be able to put a token there instead of a password. It works! :) 

That fix to the dashboard that you mention is not yet released in the docker container version of Grimoirelab I assume? Because I do see it on my dashboard. Any idea when a new version of the docker-based release can be expected?

**Comment by valeriocos** [comment]
thank you for your feedback! it should be available in this release, I'll check with the team and let you know tomorrow

**Comment by valeriocos** [comment]
Sorry for the late reply. The [fix](https://github.com/chaoss/grimoirelab-elk/commit/45ac7a8ef824bc8c5f62901c80c87ba509857ac1) is not available in the current community docker image (https://hub.docker.com/u/grimoirelab). @jgbarah could you regenerate the images when possible?

@svdo, in the meanwhile you can use the docker image available at: https://hub.docker.com/layers/bitergia/mordred/grimoirelab-0.2.30/images/sha256-ca5d6e5d521918716c0144a07ed5b908afca26bda1ffbdd08ad9253949685c07

Your docker-compose should look like:
```
redis:
  image: redis

mordred:
  restart: on-failure:5
  image: bitergia/mordred:grimoirelab-0.2.30
  volumes:
    - /home/docker/container:/home/bitergia/conf
    - /home/docker/logs:/home/bitergia/logs
    - /home/docker/storage:/home/bitergia/.perceval
  links:
    - redis
  external_links:
    - elastic_elasticsearch_1:elasticsearch
    - mariadb_mariadb_1:mariadb
    - elastic_kibiter_1:kibiter

  log_driver: "json-file"
  log_opt:
      max-size: "100m"
      max-file: "3"
``` 

Note that this requires that you have containers for elasticsearch, mariadb and kbiter in your machine (you can rely on the docker-compose here if this helps: https://github.com/chaoss/grimoirelab-sirmordred#source-code-and-docker). The structure of the docker folder is the following:
```
.
├── container
│   ├── projects.json
│   └── setup.cfg
├── logs
└── storage
```

The setup.cfg and projects.json will be similar to these ones: 
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/setup.cfg
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/projects.json

Hope this helps!
