### ISSUE TITLE
Howto support visualizing departments in Kibiter (Innersource usecase)

### ISSUE THREAD

**Issue by marcofranssen** [chaoss/grimoirelab-sirmordred#479]
Currently I'm exploring how we can visualize innersource contributions across departments within our organizations.

It would for example be great if I could use the Organizations feature as departments, however for that I need something more advanced then email/domain matching. 

- What are the thoughts of the community on this?
- Is this usecase already implemented by someone?
- Who would like to brainstorm about how this feature could be added for innersource?
- Anyone any thoughts on how to implement such feature?

I hope this feature could get some traction in the community so we can add it to Grimoirelab.

**Comment by valeriocos** [comment]
This feature is already supported by the platform (see https://github.com/chaoss/grimoirelab-elk/pull/805), but ATM we don't have default Sigils dashboards exploiting this feature.

The field `author_multi_org_names` (in the enriched indexes) contains the different organizations[1] the user belongs to. This field is automatically populated by SortingHat (the identities management system of GrimoireLab) during the enrichment phase. To add organizations to SortingHat and affiliated/enroll people to them, you can do it:
- manually via HatStall, which is the Web UI of SortingHat (available at port 8000 in the docker-compose https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml#L12). Hatstall documentation is available at: https://github.com/chaoss/grimoirelab-hatstall/tree/master/docs 
- automatically via a YAML file, which path is declared in the param `identities_file` within the setup.cfg https://github.com/chaoss/grimoirelab-sirmordred#sortinghat. The structure of the YAML file is shown below (you can find additional details at https://gitlab.com/Bitergia/c/FAQ/-/tree/master/_old_stuff/identities).
```
- profile:
    name: Wile E. Coyote
  enrollments:
    - organization: ACME <--- company
      end: 2014-09-01
    - organization: Umbrella <--- company
      start: 2014-10-01
      end: 2017-11-31
    - organization: X dept <-- department
      start: 2015-12-01
    - organization: Crafting <-- skill
      start: 2013-01-01
      end: 2018-01-01
  email:
    - willy@umbrella.com
  github:
    - willy

```

Hope this helps

[1] an organization can be anything such as a department or a technical skill (e.g., python, java)
